# Tensorflow Fundamentals

Tensorflow has two main components - Graphs and Sessions <br>
Variable gets added to Graph. Graph defines/states computation but does not perform them <br>
Different computations can be equated to each other hence linked and called a Graph

Session is a way to execute a part or all of the graph. It allocates memory and resources required for execution of operations defined <br>
Some times, sessions would have to be created to execute parts of Graphs defined

In [1]:
import tensorflow as tf

In [2]:
print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/sdevaraju/miniconda3/envs/ML_GPU/lib/python3.9/site-packages/tensorflow/_api/v2/version/__init__.py'>


## Tensors

Vector generalized to higher dimensions. Each tensor has a data type and shape. <br>
Data Type e.g float32, int32 <br>
Shape: Form of data <br>
Each tensor represents a partially defined computation that will produce a value

## Creating a Tensor

In [3]:
str_var = tf.Variable("this is a test string", tf.string)
int_var = tf.Variable(42, tf.int16)
flot_var = tf.Variable(3.14, tf.float64)

## Rank/Degree of Tensors
It defines the number of dimensions involved in the tensor. <br>
Deepest level of a nested list

In [4]:
rank1_tensor = tf.Variable(["Test", "NewStr"], tf.string)
rank2_tensor = tf.Variable([["test", "str1"], ["test2", "str2"]], tf.string)

In [5]:
display(tf.rank(rank1_tensor))
display(tf.rank(rank2_tensor))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of Tensor
Defines the number of elements in each dimension

In [6]:
display(rank1_tensor.shape)
display(rank2_tensor.shape)

TensorShape([2])

TensorShape([2, 2])

## Changing Shape

In [17]:
tensor1 = tf.ones([1,4,3])  # Number of sub arrays, rows, columns
display(tensor1)
tensor2 = tf.reshape(tensor1, [1, 3, 4])
display(tensor2)
tensor3 = tf.reshape(tensor1, [2, -1]) # -1 tells the tensor to infer size of dimension in that place [2, 6] here
display(tensor3)

<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

## Types of Tensors
- Variable
- Constant
- Placeholder
- SparseTensor

Aside from ```Variable```, all of above are immutable.

## Evaluating Tensors

In [ ]:
with tf.Session() as sess: #Creates a session using default graph
    tensor.eval()